.TH pdfannot 1 "Sept. 28, 2019"

.
.
.
.SH NAME

pdfannot - extract annotations and actions from PDF files

.
.
.
.SH SYNOPSIS

.B pdfannot
[\fI-t\fP]
[\fI-w\fP]
[\fI-d\fP]
[\fI-h\fP]
.I file.pdf
[\fIpagenumber\fP]

.
.
.
.SH OPTIONS

.TP
.B -t
output is text only
.TP
.B -w
output is html
.TP
.B -d
also output some text at destination of inner links
.TP
.B -h
online help

.
.
.
.SH SEE ALSO

.I pdftoroff(1)

