.TH pdfaddannotation 1 "May 17, 2026"

.
.
.
.SH NAME

pdfaddannotation - add a text annotation to a pdf file

.
.
.
.SH SYNOPSIS

.B pdfannot
[\fI-o output.pdf\fP]
[\fI-h\fP]
.I file.pdf
.I page
.I text
[\fIx y\fP|\fIsearch\fP]

.
.
.
.SH OPTIONS

.TP
.BI -o " output.pdf
output file; defaults to
.I file-annot.pdf

.TP
.B -h
help

.
.
.
.SH DESCRIPTION

Add a text annotation to a page of a pdf file.

The position is specified in two alternative ways:

.TP
.I x y
the coordinates in the page
.TP
.I search
the string where the annotation is added; the first occurrence in case of
multiple ones

.P
If neither is given, the annotation is placed near the upper-left corner.

.
.
.
.SH SEE ALSO

.I pdfannot(1)

