.TH pdfannotation 1 "May 17, 2026"

.
.
.
.SH NAME

pdfannotation - view or add text annotations

.
.
.
.SH SYNOPSIS

.TP 14
.BI pdfannotation " " [ "-o output.pdf" ] " " [ "-a text" ] " " [ "-r" ] \
" " [ "-l" ] " " [ "-v" ] " " [ "-h" ]
.BI "" file.pdf " " page " ["x " " y | "search" ]

.
.
.
.SH OPTIONS AND ARGUMENTS

.TP
.BI -o " output.pdf
output file; defaults to
.I file-annot.pdf

.TP
.BI -a " text
add a text annotation

.TP
.B -r
remove or change annotation

.TP
.B -l
print location and icon of annotations

.TP
.B -v
verbose

.TP
.B -h
help

.TP
.I file.pdf
input file

.TP
.I page
page number

.TP
.BI "" x " " y | search
position


.
.
.
.SH DESCRIPTION

View, add or change text annotations.

With no arguments, all text annotations in the page are printed. With option
\fI-a\fP, a text annotation is added at the top-left corner.

A position can be given in two alternative ways: either as cooordinates
.I x y
or as a text to search for. A new annotation is placed there. Viewing is
limited to the annotation closest to there.

When \fI-a\fP is given in addition to \fI-r\fP,
the annotation is not removed but changed.

.
.
.
.SH SEE ALSO

.I pdfannot(1)

