#!/bin/sh
#
# external script for hovacui
#
# l: show annotation and actions in the current page in a browser
# s: save the document

if [ "$1" = 'l' ];
then
	pdfannot -w -d "$2" $3 > hovacui-out.html
	[ $? = 0 ] && rm hovacui-out.html && exit

	if [ "$DISPLAY" = "" ];
	then
		elinks -remote 'openUrl(hovacui-out.html,new-tab)'
		elinks -remote 'reload()'
		exit
	fi

	if [ "$BROWSER" != "" ];
	then
		$BROWSER hovacui-out.html
		exit
	fi
fi

if [ "$1" = 's' ];
then
	I=1
	while [ -e selection-$I.pdf ];
	do
		I=$((I+1))
	done

	cp "$2" selection-$I.pdf
fi

