#!/bin/sh
#
# external script for hovacui
#
# l: show annotation and actions in the current page in a browser
# s: save the document

# save parameters

if false;
then
	echo "1: >>>$1<<<" >> hovacui-out.txt
	echo "2: >>>$2<<<" >> hovacui-out.txt
	echo "3: >>>$3<<<" >> hovacui-out.txt
	echo "4: >>>$4<<<" >> hovacui-out.txt
	echo "5: >>>$5<<<" >> hovacui-out.txt
	echo "6: >>>$6<<<" >> hovacui-out.txt
	echo "7: >>>$7<<<" >> hovacui-out.txt
fi

# links in page

if [ "$1" = 'l' ];
then
	pdfannot -w -d "$2" $3 > hovacui-out.html
	[ $? = 0 ] && rm hovacui-out.html && echo -n "no links in page" && exit

	if [ "$DISPLAY" = "" ];
	then
		elinks -remote 'openUrl(hovacui-out.html,new-tab)' \
			> /dev/null 2>&1
		[ $? != 0 ] && echo -n "elinks not running" && exit
		elinks -remote 'reload()'
		echo -n "passed links to elinks"
		exit
	fi

	if [ "$BROWSER" != "" ];
	then
		$BROWSER hovacui-out.html
		echo -n "passed links to $BROWSER"
		exit
	fi

	echo -n "no browser available"
fi

# save a copy of the document

if [ "$1" = 's' ];
then
	I=1
	while [ -e selection-$I.pdf ];
	do
		I=$((I+1))
	done

	cp "$2" selection-$I.pdf
	echo -n "saved as selection-$I.pdf"
fi

# copy text in page or rectangle for pasting

if [ "$1" = 'y' ];
then
	if [ "$7" != "[]" ];
	then
		BOX="-b $7"
	else
		T=$(echo $5 | tr - , | tr -d '[]')
		TX1=$(echo $T | cut -d, -f1 | cut -d. -f1)
		TY1=$(echo $T | cut -d, -f2 | cut -d. -f1)
		TX2=$(echo $T | cut -d, -f3 | cut -d. -f1)
		TY2=$(echo $T | cut -d, -f4 | cut -d. -f1)
		D=$(echo $6 | tr - , | tr -d '[]')
		DX1=$(echo $D | cut -d, -f1 | cut -d. -f1)
		DY1=$(echo $D | cut -d, -f2 | cut -d. -f1)
		DX2=$(echo $D | cut -d, -f3 | cut -d. -f1)
		DY2=$(echo $D | cut -d, -f4 | cut -d. -f1)
		BOX="-b ["
		BOX=$BOX$([ $TX1 -gt $DX1 ] && echo $TX1 || echo $DX1),
		BOX=$BOX$([ $TY1 -gt $DY1 ] && echo $TY1 || echo $DY1)-
		BOX=$BOX$([ $TX2 -lt $DX2 ] && echo $TX2 || echo $DX2),
		BOX=$BOX$([ $TY2 -lt $DY2 ] && echo $TY2 || echo $DY2)]
	fi
	# pdftoroff -t -i $3:$3 $BOX "$2" | sed '/./,$ ! d' >> hovacui-out.txt
	{
		pdftoroff -t -i $3:$3 $BOX "$2" | \
		sed '/./,$ ! d' | $COPIER 2>&1;
		[ "$?" = 0 ] && echo -n "text copied";
	} | tr '\n' ' '
fi

# edit the notes of the pdf file

if [ "$1" = 'A' ] || [ "$1" = 'N' ] || [ "$1" = 'E' ];
then
	BASE=$(echo "$2" | sed -e 's,.pdf,,' -e 's,$,-notes.txt,')

	[ "$1" = 'N' ] && CHECK=true
	[ "$1" = 'E' ] && CHECK=true
	[ "$1" = 'N' ] && EDIT=true
	[ "$1" = 'A' ] && EDIT=true

	if [ -e "$BASE" ];
	then
		if ! [ -f "$BASE" ];
		then
			echo -n "$BASE is not a regular file"
			exit 1
		fi
		if $CHECK false && \
		   grep -A2 "^## Page $3$" "$BASE" | tail -2 | grep -q "^##";
		then
			echo -n "no notes for page $3, next: "
			sed '
			: begin
				/\n##/	{ P; D; b }
					s,\n, ,g
					N
					b begin
			' "$BASE"					| \
			sed -n "/^## Page $3 /,$ p"			| \
			{ grep -m1 '## Page [0-9]* .' || echo '  none'; } | \
			cut -d' ' -f3					| \
			tr -d '\n'
			exit 1
		fi
	else
		if $CHECK false;
		then
			echo -n "no notes for page $3"
			exit 1
		fi
		echo "# $(basename "$2")" > "$BASE"
		echo >> "$BASE"
		for P in $(seq 1 $4);
		do
			echo "## Page $P" >> "$BASE"
			echo >> "$BASE"
		done
		echo '## End' >> "$BASE"
	fi

	if $EDIT false;
	then
		vi +"/## Page $3$" "$BASE" < /dev/tty > /dev/tty 2> /dev/tty
		setterm --cursor off > /dev/tty
	else
		echo -n "notes for page $3"
	fi
fi

