#!/bin/bash
#
# operate on a point or rectangle of a pdf file
#	clip all pages
#	erase rectangle (draw in white)
#	cover rectangle (draw in black)
#	write text

#SIMULATE=echo

# tty settings

clear
PREVSTTY=$(stty -g)
onexit() {
	setterm --cursor off
	stty $PREVSTTY
}
trap onexit EXIT
stty icrnl onlcr echo icanon
setterm --cursor on

# arguments

echo "$@"
KEY="$1"
ID="$2"
FILE="$3"
PAGE="$4"
BOXNUMBER="$5"
SCROLLX="$6"
SCROLLY="$7"
TOTPAGES="$8"
TEXTBOX="$9"
DEST="${10}"
RECT="${11}"

echo $RECT

# arguments

X0=$(echo "$RECT" | cut -d, -f1 | cut -d[ -f2)
Y0=$(echo "$RECT" | cut -d, -f2 | cut -d- -f1)
X1=$(echo "$RECT" | cut -d- -f2 | cut -d, -f1)
Y1=$(echo "$RECT" | cut -d, -f3 | cut -d] -f1)
CORNER="[$X0,$Y0]"
echo "file $FILE"
echo "page $PAGE"
echo "box $RECT"
echo "corner $CORNER"

# output file

EDIT=${FILE%%.pdf}-edit-%d.pdf
I=1
while [ -f $(printf $EDIT $I) ];
do
	I=$((I+1))
done
OUT=$(printf $EDIT $I)
echo $OUT

# commands

COMMANDS='clip erase cover exit'
[ $X0 = $X1 ] && [ $Y0 = $Y1 ] && COMMANDS='write exit'
N=$(echo $COMMANDS | wc -w)

# operate on file

PS3="choose command [1-$N]: "
select COMMAND in $COMMANDS;
do
	case $COMMAND in
		clip)
			$SIMULATE \
			pdfcut -o "$OUT" -p "$RECT" "$FILE"
			echo -n "clipped to $OUT" 1>&3;;
		erase)
			echo erase "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				color white filledbox "$RECT"
			echo -n "erased in $OUT" 1>&3;;
		cover)
			echo cover "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				filledbox "$RECT"
			echo -n "covered in $OUT" 1>&3;;
		write)
			echo write at "$CORNER" in page "$PAGE" of file "$FILE"
			echo -n "string to write: "
			read S
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				moveto "$CORNER" print "$S"
			echo -n "written to $OUT" 1>&3;;
		exit)
			echo nothing done;;
	esac
	break
done

# sleep 5

