#!/bin/bash
#
# operate on a point or rectangle of a pdf file
#	emphasize
#	clip all pages
#	erase rectangle (draw in white)
#	cover rectangle (draw in black)
#	write text

#SIMULATE=echo

# tty settings

clear
PREVSTTY=$(stty -g)
onexit() {
	setterm --cursor off
	stty $PREVSTTY
}
trap onexit EXIT
stty icrnl onlcr echo icanon
setterm --cursor on

# arguments

echo "$@"
KEY="$1"
ID="$2"
FILE="$3"
PAGE="$4"
BOXNUMBER="$5"
SCROLLX="$6"
SCROLLY="$7"
TOTPAGES="$8"
TEXTBOX="$9"
DEST="${10}"
RECT="${11}"

[ $RECT = '[]' ] && RECT="$TEXTBOX"
echo $RECT

# coordinates

X0=$(echo "$RECT" | cut -d, -f1 | cut -d[ -f2)
Y0=$(echo "$RECT" | cut -d, -f2 | cut -d- -f1)
X1=$(echo "$RECT" | cut -d- -f2 | cut -d, -f1)
Y1=$(echo "$RECT" | cut -d, -f3 | cut -d] -f1)
CORNER="[$X0,$Y0]"
echo "file $FILE"
echo "page $PAGE"
echo "box $RECT"
echo "corner $CORNER"

# output file

BASE=${FILE%%.pdf}
BASE=${BASE%%-edit-*}
EDIT=${BASE}-edit-%d.pdf
I=1
while [ -f $(printf $EDIT $I) ];
do
	I=$((I+1))
done
OUT=$(printf $EDIT $I)
echo $OUT

# commands

COMMANDS='emphasize clip_page clip erase cover exit'
[ $X0 = $X1 ] && [ $Y0 = $Y1 ] && COMMANDS='write red exit'
N=$(echo $COMMANDS | wc -w)

# operate on file

PS3="choose command [1-$N]: "
select COMMAND in $COMMANDS;
do
	case $COMMAND in
		emphasize)
			echo emphasize "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				color [1.0,0.0,0.0,0.5] filledbox "$RECT";;
		clip_page)
			echo clip page "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				emptypage clip "$RECT" paste;;
		clip)
			echo clip "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" \
				emptypage clip "$RECT" paste;;
		erase)
			echo erase "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				color white filledbox "$RECT";;
		cover)
			echo cover "$RECT" of page "$PAGE" of file "$FILE"
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				filledbox "$RECT";;
		red)	COLOR="color [1.0,0.0,0.0]";&
		write)
			echo write at "$CORNER" in page "$PAGE" of file "$FILE"
			echo -n "string to write: "
			read S
			$SIMULATE \
			pdfdrawover "$FILE" output "$OUT" page "$PAGE" \
				$COLOR moveto "$CORNER" print "$S";;
		exit)
			echo -n "unchanged" 1>&3
			echo 0 > pdfinteractive-ret.txt
			exit 0;;
	esac
	break
done

echo "$PAGE $BOXNUMBER $SCROLLX $SCROLLY" 1>&3
echo -n "$OUT" 1>&3
echo 1 > pdfinteractive-ret.txt
exit 1

